# Generated by Django 5.0.2 on 2025-02-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0002_alter_child_guardian_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='spc_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
    ]
