# Generated by Django 5.0.2 on 2025-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0004_rename_spc_birth_child_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
