# Generated by Django 5.0.1 on 2025-02-25 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0006_remove_child_contact_child_age_alter_child_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='guardian_name',
        ),
        migrations.AddField(
            model_name='child',
            name='guardian_firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian_lastname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian_middlename',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='child',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='code',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='child',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='fourps_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_relationship',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='lastname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='middlename',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='philhealth_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6, null=True),
        ),
    ]
