# Generated by Django 5.0.1 on 2025-02-25 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0007_remove_child_guardian_name_child_guardian_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='code',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Enter exactly 3 letters followed by 4 digits', regex='^[A-Za-z]{3}\\d{4}$')]),
        ),
    ]
