# Generated by Django 5.0.1 on 2025-02-25 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0008_alter_child_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='code',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]{3}\\d{4}$')]),
        ),
    ]
