# Generated by Django 5.0.2 on 2025-02-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0009_alter_child_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='guardian_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
