# Generated by Django 5.0.2 on 2025-02-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0010_alter_child_guardian_sex_alter_child_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='number',
            field=models.CharField(max_length=11),
        ),
    ]
