# Generated by Django 5.0.2 on 2025-02-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys42app', '0011_alter_contactnumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='child',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_lastname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_relationship',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='child',
            name='lastname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
